<a href="https://colab.research.google.com/github/FantinelBruna/pcd-unijui/blob/main/aulas/aula07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Colab colaborativo para manipulação de dados usando a biblioteca Pandas**

Para que todas as soluções propostas funcionem vamos seguir algumas regras:
* Mantenha as primeira duas células inalteradas;
* Crie cópias do dataset principal para as soluções;
* Use comentários para explicar a solução proposta;
* Insira seu nome na solução;
* A terceira célula é exemplo de como inserir.

# Importando o pandas (não altere)

In [1]:
import pandas as pd

# Criando um dataset importando um arquivo csv (não altere).

O arquivo *clima_historico_municipal.csv* contém um registro por município, identificado por código IBGE, nome e UF. Para cada município, a base informa o período de referência, a fonte climática, o método de processamento e um conjunto de variáveis mensais agregadas historicamente. As variáveis climáticas presentes são:

* tmin_*: temperatura mínima média mensal histórica
* tmax_*: temperatura máxima média mensal histórica
* temp_media_*: temperatura média mensal histórica, derivada de * tmin e tmax
* ppt_*: precipitação mensal histórica
* pet_*: evapotranspiração potencial mensal histórica
* aet_*: evapotranspiração real mensal histórica
* def_*: déficit hídrico mensal histórico

Cada sufixo mensal corresponde a um mês do ano:

*jan, fev, mar, abr, mai, jun, jul, ago, set, out, nov, dez*

Assim, por exemplo:

* temp_media_jan representa a média histórica de temperatura média para todos os janeiros do período processado
* ppt_mar representa a média histórica de precipitação para todos os meses de março do período processado
* def_set representa a média histórica de déficit hídrico para todos os meses de setembro do período processado

As unidades utilizadas são:
* temperaturas (*tmin, tmax, temp_media*): **graus Celsius (°C)**
* precipitação (*ppt*): **milímetros por mês (mm/mês)**
* evapotranspiração potencial (*pet*): **milímetros por mês (mm/mês)**
* evapotranspiração real (*aet*): **milímetros por mês (mm/mês)**
* déficit hídrico (*def*): **milímetros por mês (mm/mês)**

In [2]:
#Importando um arquivo .csv dos dados de temperatura dos municípios
df = pd.read_csv('https://raw.githubusercontent.com/andr3nf/clima_municipios_brasileiros/refs/heads/main/clima_historico_municipal.csv')

# Comandos para visualização geral dos dados

In [3]:
'''
Chamar apenas o dataframe para visualização, usa-se o nome do dataframe, neste caso o df
Quando o dataframe é muito grande ele apresenta as primeiras e últimas 5 linhas
Info: Gerson Battisti
'''
# visualiza todo DataFrame
df

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.00,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.00,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.00,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.00,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.00,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,22.55,22.67,22.73,...,2.36,9.14,31.73,50.22,79.46,103.54,92.59,35.55,3.85,0.01
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83

# Comandos para visualização parcial dos dados
Visualição rápida, mas não total, das informações

In [4]:
# Exibe as 5 primeiras linhas
display(df.head())

# Exibe as 5 últimas linhas
display(df.tail())

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5565,5222005,Vianópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,22.55,22.67,22.73,...,2.36,9.14,31.73,50.22,79.46,103.54,92.59,35.55,3.85,0.01
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83

# Como saber a quantidade de linhas e colunas do dataframe

In [5]:
# shape retorna uma tupla no formato: (linhas, colunas)
print("Quantidade de linhas:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])
print("Formato do DataFrame:", df.shape)

Quantidade de linhas: 5570
Quantidade de colunas: 91
Formato do DataFrame: (5570, 91)

# Como renomear o nome das colunas

In [7]:
# Trabalhamos em uma cópia para não alterar o DataFrame original
df_renomeado = df.copy()

# Renomeia a coluna codigo_ibge para ibge
df_renomeado.rename(columns={'codigo_ibge': 'ibge'}, inplace=True)

# Mostra as primeiras linhas para conferir
df_renomeado.head()

,ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como adicionar linhas ao dataframe

In [10]:
# Trabalhamos em uma cópia do DataFrame original
df_linhas = df.copy()

# Cria uma nova linha
nova_linha = pd.DataFrame([{
    'codigo_ibge': 9999999,
    'nome_municipio': 'Cidade Exemplo',
    'uf': 'RS'
}])

# Adiciona a nova linha ao DataFrame
df_linhas = pd.concat([df_linhas, nova_linha], ignore_index=True)

# Mostra as duas últimas linhas
df_linhas.tail(2)

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5569,5300108,Brasília,DF,1975.0,2024.0,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.0,21.92,...,3.09,8.42,31.06,46.8,74.12,99.77,91.04,40.31,2.58,0.83
5570,9999999,Cidade Exemplo,RS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Como adicionar colunas ao dataframe

In [12]:
# Trabalhamos em uma cópia
df_colunas = df.copy()

# Cria uma nova coluna com valor fixo
df_colunas['pais'] = 'Brasil'

# Cria uma coluna calculada: temperatura média de janeiro em Kelvin
df_colunas['temp_media_jan_K'] = df_colunas['temp_media_jan'] + 273.15

# Mostra algumas colunas
df_colunas[['nome_municipio', 'uf', 'pais', 'temp_media_jan', 'temp_media_jan_K']].head()

          nome_municipio  uf    pais  temp_media_jan  temp_media_jan_K
0  Alta Floresta D'Oeste  RO  Brasil           25.18            298.33
1              Ariquemes  RO  Brasil           25.29            298.44
2                 Cabixi  RO  Brasil           25.85            299.00
3                 Cacoal  RO  Brasil           24.69            297.84
4             Cerejeiras  RO  Brasil           25.84            298.99

# Como deletar linhas

In [13]:
# Trabalhamos em uma cópia
df_sem_linha = df.copy()

# Remove a linha de índice 0
df_sem_linha = df_sem_linha.drop(index=0)

print("Quantidade de linhas após a remoção:", df_sem_linha.shape[0])

df_sem_linha.head()

Quantidade de linhas após a remoção: 5569

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36
5,1100064,Colorado do Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.07,25.04,25.36,...,0.0,1.02,15.11,31.31,49.38,64.13,48.22,6.51,2.67,0.00

# Como deletar colunas

In [14]:
# Trabalhamos em uma cópia
df_sem_coluna = df.copy()

# Remove a coluna fonte_clima
df_sem_coluna = df_sem_coluna.drop(columns=['fonte_clima'])

print("A coluna 'fonte_clima' existe?", 'fonte_clima' in df_sem_coluna.columns)

df_sem_coluna.head()

A coluna 'fonte_clima' existe? False

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,temp_media_abr,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,25.26,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,25.54,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,25.71,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,24.87,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,25.79,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como mesclar dois dataframe

In [15]:
# Cria um DataFrame com a região de cada estado do Sul
regioes = pd.DataFrame({
    'uf': ['PR', 'SC', 'RS'],
    'regiao': ['Sul', 'Sul', 'Sul']
})

# Seleciona somente os municípios dos estados do Sul
df_sul = df[df['uf'].isin(['PR', 'SC', 'RS'])].copy()

# Faz a junção pela coluna uf
df_mesclado = pd.merge(df_sul, regioes, on='uf', how='left')

# Exibe o resultado
df_mesclado[['nome_municipio', 'uf', 'regiao']].head()

        nome_municipio  uf regiao
0               Abatiá  PR    Sul
1         Adrianópolis  PR    Sul
2        Agudos do Sul  PR    Sul
3  Almirante Tamandaré  PR    Sul
4   Altamira do Paraná  PR    Sul

# Buscar uma linha ou uma célula (linha e coluna) específica

In [16]:
# iloc utiliza a posição numérica
primeira_linha = df.iloc[0]
primeira_celula = df.iloc[0, 1]

print("Primeira linha:")
display(primeira_linha)

print("\nValor da primeira linha, segunda coluna:")
print(primeira_celula)

Primeira linha:

codigo_ibge                     1100015
nome_municipio    Alta Floresta D'Oeste
uf                                   RO
periodo_inicio                     1975
periodo_fim                        2024
                          ...
def_ago                            64.8
def_set                            46.2
def_out                           11.53
def_nov                             2.9
def_dez                            0.29
Name: 0, Length: 91, dtype: object

Valor da primeira linha, segunda coluna:
Alta Floresta D'Oeste

# Buscar linhas de forma condicional

In [17]:
# Filtra municípios do RS com temperatura mínima de julho abaixo de 8 °C
# e precipitação de janeiro acima de 180 mm/mês
filtro_rs = df[
    (df['uf'] == 'RS') &
    (df['tmin_jul'] < 8) &
    (df['ppt_jan'] > 180)
][['nome_municipio', 'uf', 'tmin_jul', 'ppt_jan']]

filtro_rs

      nome_municipio  uf  tmin_jul  ppt_jan
4673  Cambará do Sul  RS      6.26   182.21

# Buscar um dataframe parcial (Linhas e Colunas específicas)

In [18]:
# Seleciona linhas de 0 até 10 e colunas específicas pelo nome
df_parcial_loc = df.loc[
    0:10,
    ['nome_municipio', 'uf', 'temp_media_jan']
]

display(df_parcial_loc)

# Seleciona as 5 primeiras linhas e 3 primeiras colunas por posição
df_parcial_iloc = df.iloc[0:5, 0:3]

display(df_parcial_iloc)

           nome_municipio  uf  temp_media_jan
0   Alta Floresta D'Oeste  RO           25.18
1               Ariquemes  RO           25.29
2                  Cabixi  RO           25.85
3                  Cacoal  RO           24.69
4              Cerejeiras  RO           25.84
5       Colorado do Oeste  RO           25.07
6              Corumbiara  RO           25.31
7           Costa Marques  RO           26.17
8         Espigão D'Oeste  RO           24.54
9           Guajará-Mirim  RO           26.28
10                   Jaru  RO           24.88

   codigo_ibge         nome_municipio  uf
0      1100015  Alta Floresta D'Oeste  RO
1      1100023              Ariquemes  RO
2      1100031                 Cabixi  RO
3      1100049                 Cacoal  RO
4      1100056             Cerejeiras  RO

# Como agrupar valores de uma coluna. Semelhante a banco de dados: Groupby

In [19]:
# Agrupa os municípios por estado e calcula a média da temperatura de janeiro
media_jan_uf = (
    df
    .groupby('uf')['temp_media_jan']
    .mean()
    .round(2)
)

media_jan_uf

uf
AC    25.83
AL    25.77
AM    26.58
AP    26.00
BA    24.73
CE    26.68
DF    21.88
ES    24.44
GO    24.05
MA    26.53
MG    23.02
MS    25.64
MT    25.32
PA    26.15
PB    25.51
PE    24.60
PI    26.69
PR    23.13
RJ    24.42
RN    26.89
RO    25.11
RR    26.68
RS    23.58
SC    22.22
SE    26.20
SP    23.79
TO    25.37
Name: temp_media_jan, dtype: float64

# Criar um dataframe a partir de um dicionário

In [20]:
# Cria um dicionário
dados = {
    'municipio': ['São Paulo', 'Porto Alegre'],
    'uf': ['SP', 'RS'],
    'temp_media_jan': [26.63, 24.52]
}

# Converte o dicionário em DataFrame
df_dicionario = pd.DataFrame(dados)

df_dicionario

      municipio  uf  temp_media_jan
0     São Paulo  SP           26.63
1  Porto Alegre  RS           24.52

# Como deletar linhas com valores vazios

In [21]:
# Cria uma cópia e adiciona uma linha vazia apenas para demonstrar
df_vazios = df.copy()
linha_vazia = pd.DataFrame([{}])

df_vazios = pd.concat([df_vazios, linha_vazia], ignore_index=True)

print("Antes do dropna:", df_vazios.shape)

# Remove linhas que possuem valores nulos
df_vazios = df_vazios.dropna()

print("Depois do dropna:", df_vazios.shape)

Antes do dropna: (5571, 91)
Depois do dropna: (5569, 91)

# Como preencher valores vazios

In [22]:
# Cria uma cópia e adiciona uma linha vazia
df_preenchido = df.copy()
linha_vazia = pd.DataFrame([{}])

df_preenchido = pd.concat([df_preenchido, linha_vazia], ignore_index=True)

# Preenche valores nulos com 0
df_preenchido.fillna(0, inplace=True)

df_preenchido.tail()

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5566,5222054.0,Vicentinópolis,GO,1975.0,2024.0,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203.0,Vila Boa,GO,1975.0,2024.0,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302.0,Vila Propício,GO,1975.0,2024.0,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108.0,Brasília,DF,1975.0,2024.0,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83
5570,0.0,0,0,0.0,0.0,0,0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

# Comandos para inserir colunas com valores de chuva mensal

In [23]:
# Trabalhamos em uma cópia do DataFrame
df_chuva = df.copy()

# Lista das colunas de precipitação mensal
colunas_chuva = [
    'ppt_jan', 'ppt_fev', 'ppt_mar', 'ppt_abr',
    'ppt_mai', 'ppt_jun', 'ppt_jul', 'ppt_ago',
    'ppt_set', 'ppt_out', 'ppt_nov', 'ppt_dez'
]

# Soma da precipitação dos 12 meses
df_chuva['ppt_total_ano'] = df_chuva[colunas_chuva].sum(axis=1)

# Média mensal de precipitação
df_chuva['ppt_media_mensal'] = df_chuva[colunas_chuva].mean(axis=1)

# Identifica a coluna correspondente ao mês mais chuvoso
df_chuva['mes_mais_chuvoso'] = df_chuva[colunas_chuva].idxmax(axis=1)

display(
    df_chuva[
        ['nome_municipio', 'uf', 'ppt_total_ano', 'ppt_media_mensal', 'mes_mais_chuvoso']
    ].head()
)

/tmp/ipykernel_1775/1682518218.py:18: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  df_chuva['mes_mais_chuvoso'] = df_chuva[colunas_chuva].idxmax(axis=1)

          nome_municipio  uf  ppt_total_ano  ppt_media_mensal mes_mais_chuvoso
0  Alta Floresta D'Oeste  RO        1580.36        131.696667          ppt_jan
1              Ariquemes  RO        2133.42        177.785000          ppt_jan
2                 Cabixi  RO        1806.50        150.541667          ppt_jan
3                 Cacoal  RO        1999.72        166.643333          ppt_jan
4             Cerejeiras  RO        1663.89        138.657500          ppt_jan